### ISSUE TITLE
Insecure primes

### ISSUE THREAD

**Issue by zLuki** [SilasDemez/verschluesselung#1]
RSA and diffie hellman should use way bigger prime numbers. Your primes are too small and therefore insecure. 
Use primes of size > 10^20

**Comment by SilasDemez** [comment]
This is a testwise implementation. You would get that if you would have seen that the primes aren't chosen but that a list of primes is fenerated and a random prime gets chosen --> extremely bad performance

**Comment by zLuki** [comment]
You can try to improve your algorithm by generating this list once and not every time the function is called. And only check for divisibility until square root of n with is a lot faster
